#!/usr/bin/env bash

################################################################################
# Slugify
#
# Ahoy, matey! This here script transforms yer landlubber strings into
# fine, seaworthy slugs fit for any URL or file name on the seven seas!
#
# Description:
#   Takes a string argument and converts it into a URL-safe slug by
#   lowercasing, replacing spaces with hyphens, stripping special
#   characters, collapsing consecutive hyphens, and trimming the edges.
#
# Usage:
#   ./slugify.sh "Your String Here"
#
# Arguments:
#   STRING    The string to slugify (required, must be quoted)
#
# Examples:
#   ./slugify.sh "Hello World"
#   ./slugify.sh "It's a Pirate's Life!"
#   ./slugify.sh "The Quick Brown Fox 123"
#
# Author: Generated by bash-project-scaffold
# Version: 1.0.0
################################################################################

set -euo pipefail

# Arrr! Mark the spot — where this script be buried
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Colors for the treasure map (output formatting)
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

################################################################################
# Usage
################################################################################

usage() {
    # Shiver me timbers! Show the crew how to use this tool
    cat <<EOF

Usage:
  $(basename "$0") "Your String Here"

Description:
  Converts a string into a URL-safe slug.

  A slug will:
    - Be converted to lowercase
    - Have spaces replaced with hyphens
    - Have non-alphanumeric/non-hyphen characters removed
    - Have consecutive hyphens collapsed into one
    - Have leading and trailing hyphens stripped

Examples:
  $(basename "$0") "Hello World"          → hello-world
  $(basename "$0") "It's a Pirate's Life!" → its-a-pirates-life
  $(basename "$0") "The Quick Brown Fox"   → the-quick-brown-fox

EOF
}

################################################################################
# Slugify Function
################################################################################

slugify() {
    local input="$1"

    # Arrr! One mighty pipeline does the work of five scallywags:
    #   1. Lowercase — no uppercasin' landlubbers allowed!
    #   2. Spaces → hyphens — walk the plank, spaces!
    #   3. Strip non-alphanumeric/non-hyphen chars — overboard, ye scurvy characters!
    #   4. Collapse consecutive hyphens — no double-crossers on this ship!
    #   5. Trim leading/trailing hyphens — trim the sails, matey!
    echo "$input" \
        | tr '[:upper:]' '[:lower:]' \
        | tr ' ' '-' \
        | sed 's/[^a-z0-9-]//g; s/-\{2,\}/-/g; s/^-*//; s/-*$//'
}

################################################################################
# Main — All hands on deck!
################################################################################

main() {
    # Avast! Make sure the crew provided a string to slugify
    if [[ $# -eq 0 ]]; then
        echo -e "${YELLOW}Blimey! Ye forgot to give me a string to slugify!${NC}" >&2
        usage
        exit 1
    fi

    # Batten down the hatches — only one argument, ye scallywag!
    if [[ $# -gt 1 ]]; then
        echo -e "${YELLOW}Arrr! Too many arguments! Wrap yer string in quotes, landlubber!${NC}" >&2
        usage
        exit 1
    fi

    local input="$1"

    # Here be the treasure — compute the slug!
    local result
    result="$(slugify "$input")"

    # Hoist the colors and print the slug on its own line for easy plunderin'
    echo ""
    echo -e "${GREEN}${result}${NC}"
}

main "$@"
