#!/usr/bin/env bash

################################################################################
# Slugify Test Script
#
# Ahoy! These here be the tests that guard our precious slugify treasure!
# Run 'em to make sure the script be seaworthy before setting sail!
#
# Description:
#   Test suite for the slugify.sh script. Verifies all slug transformation
#   rules: lowercasing, hyphen replacement, special character removal,
#   hyphen collapsing, and edge trimming.
#
# Usage:
#   ./test_slugify.sh
#
# Author: Generated by bash-project-scaffold
# Version: 1.0.0
################################################################################

set -euo pipefail

# Colors — paint the ship's mast with the results!
readonly GREEN='\033[0;32m'
readonly RED='\033[0;31m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

# Test counters — count yer doubloons
TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0

# Get directories — chart the course to the treasure
TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$TEST_DIR/.." && pwd)"
SLUGIFY_SCRIPT="$PROJECT_DIR/slugify.sh"

################################################################################
# Test Framework Functions
################################################################################

setup() {
    # Prepare the ship for testing — nothing to plunder here yet
    : # no-op setup for now
}

teardown() {
    # Swab the decks after testing
    : # no-op teardown for now
}

assert_equals() {
    local expected="$1"
    local actual="$2"
    local message="${3:-Assertion failed}"

    TESTS_RUN=$((TESTS_RUN + 1))

    if [[ "$expected" == "$actual" ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        echo "  Expected: '$expected'"
        echo "  Actual:   '$actual'"
        return 1 || true
    fi
}

assert_contains() {
    local haystack="$1"
    local needle="$2"
    local message="${3:-String should contain substring}"

    TESTS_RUN=$((TESTS_RUN + 1))

    if [[ "$haystack" == *"$needle"* ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        echo "  Haystack: $haystack"
        echo "  Needle:   $needle"
        return 1 || true
    fi
}

assert_file_exists() {
    local file="$1"
    local message="${2:-File should exist: $file}"

    TESTS_RUN=$((TESTS_RUN + 1))

    if [[ -f "$file" ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        return 1 || true
    fi
}

# Helper: run slugify and return only the slug line (strip color codes + blank lines)
run_slugify() {
    local input="$1"
    # Arrr! Strip ANSI escape codes and grab the non-empty line that be our slug
    "$SLUGIFY_SCRIPT" "$input" 2>/dev/null \
        | sed 's/\x1b\[[0-9;]*m//g' \
        | grep -v '^[[:space:]]*$' \
        | tail -1
}

################################################################################
# Test Cases — All hands on deck!
################################################################################

test_script_exists_and_executable() {
    echo ""
    echo "Testing: slugify.sh exists and is executable"

    assert_file_exists "$SLUGIFY_SCRIPT" "slugify.sh should exist"

    TESTS_RUN=$((TESTS_RUN + 1))
    if [[ -x "$SLUGIFY_SCRIPT" ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} slugify.sh is executable"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} slugify.sh is not executable"
    fi
}

test_no_args_shows_usage() {
    # Blimey! Running without args should show usage, not blow up the ship
    echo ""
    echo "Testing: no arguments shows usage message"

    local output
    output=$("$SLUGIFY_SCRIPT" 2>&1 || true)

    assert_contains "$output" "Usage:" "No-argument output should contain Usage:"
    assert_contains "$output" "slugify" "No-argument output should reference slugify"
}

test_basic_string() {
    # Ahoy! The most basic treasure: two words
    echo ""
    echo "Testing: basic string 'Hello World' → 'hello-world'"

    local result
    result="$(run_slugify "Hello World")"
    assert_equals "hello-world" "$result" "'Hello World' should slugify to 'hello-world'"
}

test_mixed_case() {
    # Arrr, uppercase be no match for our trusty tr command!
    echo ""
    echo "Testing: mixed case 'The Quick Brown Fox' → 'the-quick-brown-fox'"

    local result
    result="$(run_slugify "The Quick Brown Fox")"
    assert_equals "the-quick-brown-fox" "$result" "'The Quick Brown Fox' should slugify to 'the-quick-brown-fox'"
}

test_special_characters() {
    # Walk the plank, ye commas and exclamation marks!
    echo ""
    echo "Testing: special characters 'Hello, World!' → 'hello-world'"

    local result
    result="$(run_slugify "Hello, World!")"
    assert_equals "hello-world" "$result" "'Hello, World!' should slugify to 'hello-world'"
}

test_multiple_spaces() {
    # Shiver me timbers! Multiple spaces collapse into one hyphen
    echo ""
    echo "Testing: multiple spaces 'foo   bar' → 'foo-bar'"

    local result
    result="$(run_slugify "foo   bar")"
    assert_equals "foo-bar" "$result" "'foo   bar' should slugify to 'foo-bar'"
}

test_leading_trailing_spaces() {
    # Trim the sails — leading and trailing spaces must go!
    echo ""
    echo "Testing: leading/trailing spaces '  hello world  ' → 'hello-world'"

    local result
    result="$(run_slugify "  hello world  ")"
    assert_equals "hello-world" "$result" "'  hello world  ' should slugify to 'hello-world'"
}

test_already_a_slug() {
    # A slug that already be a slug should remain unchanged, savvy?
    echo ""
    echo "Testing: already a slug 'hello-world' → 'hello-world'"

    local result
    result="$(run_slugify "hello-world")"
    assert_equals "hello-world" "$result" "'hello-world' should slugify to 'hello-world'"
}

test_with_numbers() {
    # Numbers be welcome on this ship — treat 'em like alphanumeric crew
    echo ""
    echo "Testing: numbers 'Hello World 123' → 'hello-world-123'"

    local result
    result="$(run_slugify "Hello World 123")"
    assert_equals "hello-world-123" "$result" "'Hello World 123' should slugify to 'hello-world-123'"
}

test_apostrophes_and_special_chars() {
    # Arrr! Apostrophes and exclamation marks be banished from this slug!
    echo ""
    echo "Testing: apostrophes and special chars \"It's a Pirate's Life!\" → 'its-a-pirates-life'"

    local result
    result="$(run_slugify "It's a Pirate's Life!")"
    assert_equals "its-a-pirates-life" "$result" "\"It's a Pirate's Life!\" should slugify to 'its-a-pirates-life'"
}

test_output_on_new_line() {
    # The slug must be preceded by a blank line — easy to plunder with a copy!
    echo ""
    echo "Testing: slug output is preceded by a blank line (clear separator)"

    local raw_output
    raw_output=$("$SLUGIFY_SCRIPT" "Hello World" 2>/dev/null)

    # Strip ANSI color codes so we can inspect the raw structure
    local plain_output
    plain_output="$(echo "$raw_output" | sed 's/\x1b\[[0-9;]*m//g')"

    # The output should contain a blank line followed by the slug, i.e. two consecutive newlines
    # We verify by checking that at least one empty line exists in the output
    TESTS_RUN=$((TESTS_RUN + 1))
    if echo "$plain_output" | grep -qP '^$'; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} Output should contain a blank line before the slug"
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} Output should contain a blank line before the slug"
        echo "  Raw output: $(echo "$plain_output" | cat -A)"
    fi

    # Also verify the slug itself appears on the last non-empty line
    local last_line
    last_line="$(echo "$plain_output" | grep -v '^[[:space:]]*$' | tail -1)"
    assert_equals "hello-world" "$last_line" "The final non-empty line should be the slug"
}

test_too_many_args_shows_usage() {
    # Batten down the hatches — too many args be a mistake, matey!
    echo ""
    echo "Testing: too many arguments shows usage message"

    local output
    output=$("$SLUGIFY_SCRIPT" "hello" "world" 2>&1 || true)

    assert_contains "$output" "Usage:" "Too-many-args output should contain Usage:"
}

################################################################################
# Main Test Runner — All hands on deck, run the gauntlet!
################################################################################

run_all_tests() {
    echo "========================================"
    echo "Running Slugify Tests"
    echo "Arrr! May the best slug win!"
    echo "========================================"

    setup

    # Run all tests — every last one, ye hear?
    test_script_exists_and_executable
    test_no_args_shows_usage
    test_basic_string
    test_mixed_case
    test_special_characters
    test_multiple_spaces
    test_leading_trailing_spaces
    test_already_a_slug
    test_with_numbers
    test_apostrophes_and_special_chars
    test_output_on_new_line
    test_too_many_args_shows_usage

    teardown

    # Tally the treasure and report to the captain!
    echo ""
    echo "========================================"
    echo "Test Summary"
    echo "========================================"
    echo "Tests run:    $TESTS_RUN"
    echo -e "Tests passed: ${GREEN}$TESTS_PASSED${NC}"
    echo -e "Tests failed: ${RED}$TESTS_FAILED${NC}"

    if [[ $TESTS_FAILED -eq 0 ]]; then
        echo -e "${GREEN}All tests passed! Hoist the Jolly Roger!${NC}"
        exit 0
    else
        echo -e "${RED}Some tests failed! Man the lifeboats!${NC}"
        exit 1
    fi
}

# Set sail!
run_all_tests
