#!/usr/bin/env bash


################################################################################
# GitHub Label Manager
#
# Description:
#   Manages GitHub repository labels based on conventional commit conventions.
#   This script can create, update, delete, and list labels with predefined
#   colors and descriptions for conventional commit types.
#
# Usage:
#   ./github_label_manager.sh [COMMAND] [OPTIONS]
#
# Commands:
#   create                  Create all conventional commit labels
#   update                  Update existing labels with new colors/descriptions
#   delete [LABEL]          Delete a specific label or all conventional labels
#   list                    List all labels in the repository
#
# Options:
#   -o, --org ORG           GitHub organization/user (required)
#   -r, --repo REPO         Repository name (required)
#   -t, --token TOKEN       GitHub token (optional if GITHUB_TOKEN/GH_TOKEN set)
#   -d, --dry-run           Show what would be done without making changes
#   -v, --verbose           Enable verbose output
#   -h, --help              Display this help message
#
# Examples:
#   ./github_label_manager.sh create --org myorg --repo myrepo
#   ./github_label_manager.sh list --org myorg --repo myrepo
#   ./github_label_manager.sh delete feat --org myorg --repo myrepo
#   ./github_label_manager.sh update --org myorg --repo myrepo --dry-run
#
# Environment Variables:
#   GITHUB_ORG              GitHub organization/user
#   GITHUB_REPO             Repository name
#   GITHUB_TOKEN            GitHub personal access token
#   GH_TOKEN                Alternative GitHub token (GitHub CLI format)
#
# Author: Generated by bash-project-scaffold
# Version: 1.0.0
################################################################################

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source logging library
# shellcheck source=lib/logging.sh
source "$SCRIPT_DIR/lib/logging.sh"

# Load environment variables if .env exists
if [[ -f "$SCRIPT_DIR/../.env" ]]; then
    # shellcheck source=../.env
    set -a
    source "$SCRIPT_DIR/../.env"
    set +a
fi

################################################################################
# Configuration
################################################################################

# GitHub API configuration
GITHUB_API_URL="https://api.github.com"
GITHUB_ORG="${GITHUB_ORG:-}"
GITHUB_REPO="${GITHUB_REPO:-}"
GITHUB_TOKEN="${GITHUB_TOKEN:-${GH_TOKEN:-}}"

# Script options
DRY_RUN=false
VERBOSE=false
COMMAND=""
LABEL_TO_DELETE=""

# Conventional commit label definitions
# Format: name|color|description
CONVENTIONAL_LABELS=(
    "feat|00FF00|A new feature"
    "fix|FF0000|A bug fix"
    "docs|0000FF|Documentation only changes"
    "style|FFFFFF|Changes that do not affect the meaning of the code"
    "refactor|FFA500|Code changes that neither fix a bug nor add a feature"
    "test|FFFF00|Adding missing tests or correcting existing tests"
    "chore|808080|Changes to the build process or auxiliary tools"
    "perf|00FF00|A code change that improves performance"
    "ci|0000FF|Changes to CI configuration files and scripts"
    "build|808080|Changes that affect the build system or external dependencies"
    "revert|FFA500|Reverts a previous commit"
    "BREAKING CHANGE|FF0000|Breaking changes"
)

################################################################################
# Functions
################################################################################

show_help() {
    # Extract help from the header comment block until the first code line
    sed -n '/^#!/,/^set -euo pipefail/p' "$0" | grep '^#' | grep -v '#!/usr/bin/env' | sed 's/^# \?//'
    exit 0
}

validate_github_config() {
    if [[ -z "$GITHUB_ORG" ]]; then
        log_error "GitHub organization is required. Set GITHUB_ORG or use --org"
        exit 1
    fi

    if [[ -z "$GITHUB_REPO" ]]; then
        log_error "GitHub repository is required. Set GITHUB_REPO or use --repo"
        exit 1
    fi

    if [[ -z "$GITHUB_TOKEN" ]]; then
        log_error "GitHub token is required. Set GITHUB_TOKEN or GH_TOKEN"
        exit 1
    fi

    log_debug "GitHub config validated: $GITHUB_ORG/$GITHUB_REPO"
}

github_api_call() {
    local method="$1"
    local endpoint="$2"
    local data="${3:-}"

    local url="$GITHUB_API_URL/repos/$GITHUB_ORG/$GITHUB_REPO/$endpoint"

    if [[ "$DRY_RUN" == "true" ]]; then
        log_info "[DRY RUN] Would call: $method $url"
        [[ -n "$data" ]] && log_debug "[DRY RUN] Data: $data"
        return 0
    fi

    local curl_args=(
        -X "$method"
        -H "Authorization: token $GITHUB_TOKEN"
        -H "Accept: application/vnd.github.v3+json"
        -H "User-Agent: github-label-manager/1.0.0"
    )

    if [[ -n "$data" ]]; then
        curl_args+=(-H "Content-Type: application/json" -d "$data")
    fi

    curl_args+=("$url")

    log_debug "API call: $method $url"
    if [[ -n "$data" ]]; then
        log_debug "Data: $data"
    fi

    local response
    local http_code

    response=$(curl -s -w "%{http_code}" "${curl_args[@]}")
    http_code=$(echo "$response" | tail -c 3)
    response=$(echo "$response" | head -n -1)

    if [[ "$http_code" -lt 200 || "$http_code" -gt 299 ]]; then
        log_error "GitHub API error ($http_code): $response"
        return 1
    fi

    echo "$response"
}

create_label() {
    local name="$1"
    local color="$2"
    local description="$3"

    local data
    data=$(jq -n --arg name "$name" --arg color "$color" --arg description "$description" \
        '{name: $name, color: $color, description: $description}')

    log_info "Creating label: $name ($color) - $description"
    github_api_call "POST" "labels" "$data" > /dev/null
}

update_label() {
    local name="$1"
    local color="$2"
    local description="$3"

    local data
    data=$(jq -n --arg color "$color" --arg description "$description" \
        '{color: $color, description: $description}')

    log_info "Updating label: $name ($color) - $description"
    github_api_call "PATCH" "labels/$(urlencode "$name")" "$data" > /dev/null
}

delete_label() {
    local name="$1"

    log_info "Deleting label: $name"
    github_api_call "DELETE" "labels/$(urlencode "$name")" > /dev/null
}

urlencode() {
    local string="$1"
    local encoded=""

    for ((i = 0; i < ${#string}; i++)); do
        local char="${string:i:1}"
        case "$char" in
            [a-zA-Z0-9.~_-])
                encoded+="$char"
                ;;
            ' ')
                encoded+="%20"
                ;;
            *)
                printf -v encoded '%s%%%02X' "$encoded" "'$char"
                ;;
        esac
    done

    echo "$encoded"
}

list_labels() {
    log_info "Fetching labels from $GITHUB_ORG/$GITHUB_REPO"

    local response
    response=$(github_api_call "GET" "labels")

    echo "$response" | jq -r '.[] | "\(.name)|\(.color)|\(.description // "")"'
}

get_conventional_label_names() {
    local names=()
    for label in "${CONVENTIONAL_LABELS[@]}"; do
        IFS='|' read -r name _ _ <<< "$label"
        names+=("$name")
    done
    echo "${names[@]}"
}

create_all_labels() {
    log_info "Creating all conventional commit labels"

    for label in "${CONVENTIONAL_LABELS[@]}"; do
        IFS='|' read -r name color description <<< "$label"
        if ! create_label "$name" "$color" "$description"; then
            log_warn "Failed to create label: $name"
        fi
    done
}

update_all_labels() {
    log_info "Updating all conventional commit labels"

    for label in "${CONVENTIONAL_LABELS[@]}"; do
        IFS='|' read -r name color description <<< "$label"
        if ! update_label "$name" "$color" "$description"; then
            log_warn "Failed to update label: $name"
        fi
    done
}

delete_conventional_labels() {
    log_info "Deleting all conventional commit labels"

    local label_names
    mapfile -t label_names < <(get_conventional_label_names)

    for name in "${label_names[@]}"; do
        if ! delete_label "$name"; then
            log_warn "Failed to delete label: $name"
        fi
    done
}

################################################################################
# Argument Parsing
################################################################################

parse_arguments() {
    # Check for help first
    for arg in "$@"; do
        if [[ "$arg" == "--help" ]] || [[ "$arg" == "-h" ]]; then
            show_help
        fi
    done

    # First argument should be the command
    if [[ $# -eq 0 ]]; then
        log_error "Command is required. Use --help for usage information"
        exit 1
    fi

    COMMAND="$1"
    shift

    case "$COMMAND" in
        create|update|list)
            # These commands don't take additional label arguments
            ;;
        delete)
            # delete can take an optional label name
            if [[ $# -gt 0 && ! "$1" =~ ^- ]]; then
                LABEL_TO_DELETE="$1"
                shift
            fi
            ;;
        *)
            log_error "Unknown command: $COMMAND"
            echo "Valid commands: create, update, delete, list"
            exit 1
            ;;
    esac

    while [[ $# -gt 0 ]]; do
        case $1 in
            -o|--org)
                GITHUB_ORG="$2"
                shift 2
                ;;
            -r|--repo)
                GITHUB_REPO="$2"
                shift 2
                ;;
            -t|--token)
                GITHUB_TOKEN="$2"
                shift 2
                ;;
            -d|--dry-run)
                DRY_RUN=true
                shift
                ;;
            -v|--verbose)
                VERBOSE=true
                LOG_LEVEL="DEBUG"
                shift
                ;;
            -h|--help)
                show_help
                ;;
            *)
                log_error "Unknown option: $1"
                echo "Use --help for usage information"
                exit 1
                ;;
        esac
    done
}

################################################################################
# Main Function
################################################################################

main() {
    log_info "Starting GitHub Label Manager"
    log_debug "Command: $COMMAND, Dry run: $DRY_RUN"

    # Validate GitHub configuration
    validate_github_config

    case "$COMMAND" in
        create)
            create_all_labels
            log_success "All conventional commit labels created successfully!"
            ;;
        update)
            update_all_labels
            log_success "All conventional commit labels updated successfully!"
            ;;
        delete)
            if [[ -n "${LABEL_TO_DELETE:-}" ]]; then
                delete_label "$LABEL_TO_DELETE"
                log_success "Label '$LABEL_TO_DELETE' deleted successfully!"
            else
                delete_conventional_labels
                log_success "All conventional commit labels deleted successfully!"
            fi
            ;;
        list)
            list_labels
            ;;
        *)
            log_error "Unknown command: $COMMAND"
            exit 1
            ;;
    esac
}

################################################################################
# Entry Point
################################################################################

# Parse command-line arguments
parse_arguments "$@"

# Run main function
main
