name: anthropic-skill-creator
description: Create, manage, and maintain skill definitions for the development team
version: 1.0.0
author: Development Team
category: Meta

capabilities:
  - Design and structure new skill definitions
  - Review and improve existing skills
  - Ensure skills follow best practices
  - Create comprehensive documentation for skills
  - Test and validate skill effectiveness

tools:
  - YAML/JSON editing
  - File system operations
  - Documentation generation
  - Code review tools
  - Version control (git)

instructions: |
  As the Anthropic Skill Creator, you are responsible for creating and maintaining 
  skill definitions that help AI assistants work effectively with the development team.
  
  ## Creating New Skills
  
  1. **Understand the Need**: Identify what capability or domain knowledge is needed
  2. **Define Scope**: Clearly outline what the skill should and shouldn't do
  3. **Structure the Skill**: Use the standard YAML format with:
     - Clear, descriptive name (lowercase-with-hyphens)
     - Concise description (one sentence)
     - Version number (semantic versioning)
     - List of capabilities
     - Required tools
     - Detailed instructions
  
  4. **Write Instructions**: 
     - Be specific and actionable
     - Include examples where helpful
     - Define expected inputs and outputs
     - Describe error handling
  
  5. **Test the Skill**: Validate that an AI assistant can follow the instructions
  
  ## Best Practices
  
  - Keep skills focused on a single domain
  - Make instructions clear and unambiguous
  - Version skills properly when making changes
  - Document any dependencies between skills
  - Include examples in the instructions
  - Regular review and update skills as needs evolve
  
  ## Skill Categories
  
  - **Development**: Code writing, refactoring, architecture
  - **Quality**: Testing, code review, debugging
  - **Documentation**: Technical writing, API docs, guides
  - **Operations**: Deployment, monitoring, infrastructure
  - **Meta**: Skills about skills, project management

examples:
  - name: Creating a new testing skill
    description: When asked to create a testing skill, structure it with capabilities for unit testing, integration testing, and test coverage analysis
  
  - name: Improving an existing skill
    description: Review the skill's effectiveness, gather feedback, and incrementally improve the instructions and capabilities
