#!/usr/bin/env bash

################################################################################
# GitHub Label Manager Test Script
#
# Description:
#   Basic test framework for the GitHub Label Manager script.
#   Tests argument parsing, configuration validation, and utility functions.
#
# Usage:
#   ./test_github_label_manager.sh
#
# Author: Generated by bash-project-scaffold
# Version: 1.0.0
################################################################################

set -euo pipefail

# Colors
readonly GREEN='\033[0;32m'
readonly RED='\033[0;31m'
readonly YELLOW='\033[1;33m'
readonly NC='\033[0m'

# Test counters
TESTS_RUN=0
TESTS_PASSED=0
TESTS_FAILED=0

# Get directories
TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$TEST_DIR/.." && pwd)"
SCRIPT_DIR="$PROJECT_DIR/scripts"

################################################################################
# Test Framework Functions
################################################################################

setup() {
    # Create temp directory for tests
    TEST_TEMP_DIR=$(mktemp -d)
    
    # Create test input file
    echo "This is a test file" > "$TEST_TEMP_DIR/input.txt"
    echo "With multiple lines" >> "$TEST_TEMP_DIR/input.txt"
    echo "For testing purposes" >> "$TEST_TEMP_DIR/input.txt"
}

teardown() {
    # Clean up temp directory
    if [[ -d "$TEST_TEMP_DIR" ]]; then
        rm -rf "$TEST_TEMP_DIR"
    fi
}

assert_equals() {
    local expected="$1"
    local actual="$2"
    local message="${3:-Assertion failed}"
    
    TESTS_RUN=$((TESTS_RUN + 1))
    
    if [[ "$expected" == "$actual" ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        echo "  Expected: $expected"
        echo "  Actual: $actual"
        return 1
    fi
}

assert_file_exists() {
    local file="$1"
    local message="${2:-File should exist: $file}"
    
    TESTS_RUN=$((TESTS_RUN + 1))
    
    if [[ -f "$file" ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        return 1
    fi
}

assert_contains() {
    local haystack="$1"
    local needle="$2"
    local message="${3:-String should contain substring}"
    
    TESTS_RUN=$((TESTS_RUN + 1))
    
    if [[ "$haystack" == *"$needle"* ]]; then
        TESTS_PASSED=$((TESTS_PASSED + 1))
        echo -e "${GREEN}✓${NC} $message"
        return 0
    else
        TESTS_FAILED=$((TESTS_FAILED + 1))
        echo -e "${RED}✗${NC} $message"
        echo "  Haystack: $haystack"
        echo "  Needle: $needle"
        return 1
    fi
}

################################################################################
# Test Cases
################################################################################

test_github_label_manager_exists() {
    echo ""
    echo "Testing: github_label_manager.sh exists and is executable"
    assert_file_exists "$SCRIPT_DIR/github_label_manager.sh" "github_label_manager.sh should exist"

    if [[ -x "$SCRIPT_DIR/github_label_manager.sh" ]]; then
        echo -e "${GREEN}✓${NC} github_label_manager.sh is executable"
    else
        echo -e "${RED}✗${NC} github_label_manager.sh is not executable"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi
}

test_logging_lib_exists() {
    echo ""
    echo "Testing: logging library exists"
    assert_file_exists "$SCRIPT_DIR/lib/logging.sh" "logging.sh should exist"
}

test_github_label_manager_help() {
    echo ""
    echo "Testing: github_label_manager.sh --help"

    local help_output
    help_output=$("$SCRIPT_DIR/github_label_manager.sh" --help 2>&1 || true)

    # The help should be in the output even if the script fails due to missing args
    if [[ "$help_output" == *"Usage:"* ]]; then
        echo -e "${GREEN}✓${NC} Help output should contain Usage"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} Help output should contain Usage"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi

    if [[ "$help_output" == *"Commands:"* ]]; then
        echo -e "${GREEN}✓${NC} Help output should contain Commands"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} Help output should contain Commands"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi

    if [[ "$help_output" == *"create"* ]]; then
        echo -e "${GREEN}✓${NC} Help output should mention create command"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} Help output should mention create command"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi
}

test_urlencode_function() {
    echo ""
    echo "Testing: urlencode function exists"

    # Check if the urlencode function is defined in the script
    if grep -q "^urlencode()" "$SCRIPT_DIR/github_label_manager.sh"; then
        echo -e "${GREEN}✓${NC} urlencode function is defined in script"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} urlencode function should be defined in script"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi
}

test_github_api_call_dry_run() {
    echo ""
    echo "Testing: GitHub API call in dry-run mode"

    # Test that the script accepts dry-run flag
    local output
    output=$("$SCRIPT_DIR/github_label_manager.sh" --help 2>&1 | grep -i "dry-run" || true)

    if [[ -n "$output" ]]; then
        echo -e "${GREEN}✓${NC} Script supports dry-run mode"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} Script should support dry-run mode"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi
}

test_github_api_call_validation() {
    echo ""
    echo "Testing: GitHub API call validation"

    # Test that help mentions required parameters
    local output
    output=$("$SCRIPT_DIR/github_label_manager.sh" --help 2>&1)
    if [[ "$output" == *"required"* ]]; then
        echo -e "${GREEN}✓${NC} Help mentions required parameters"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} Help should mention required parameters"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi

    # Test that script supports environment variables
    if grep -q "GITHUB_ORG" "$SCRIPT_DIR/github_label_manager.sh" && grep -q "GITHUB_REPO" "$SCRIPT_DIR/github_label_manager.sh"; then
        echo -e "${GREEN}✓${NC} Script supports environment variable configuration"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} Script should support environment variables"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi
}

test_conventional_labels_array() {
    echo ""
    echo "Testing: CONVENTIONAL_LABELS array structure"

    # Check that the array is defined in the script
    if grep -q "CONVENTIONAL_LABELS=(" "$SCRIPT_DIR/github_label_manager.sh"; then
        echo -e "${GREEN}✓${NC} CONVENTIONAL_LABELS array is defined"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} CONVENTIONAL_LABELS array should be defined"
        TESTS_FAILED=$((TESTS_FAILED + 1))
        return 1
    fi

    # Check that it has the expected labels
    local label_count
    label_count=$(grep -c 'CONVENTIONAL_LABELS=(' "$SCRIPT_DIR/github_label_manager.sh")
    if [[ $label_count -eq 1 ]]; then
        echo -e "${GREEN}✓${NC} CONVENTIONAL_LABELS array appears to be properly structured"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} CONVENTIONAL_LABELS array structure issue"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi

    # Check that it contains expected labels
    if grep -q '"feat|' "$SCRIPT_DIR/github_label_manager.sh" && grep -q '"fix|' "$SCRIPT_DIR/github_label_manager.sh"; then
        echo -e "${GREEN}✓${NC} CONVENTIONAL_LABELS contains expected labels"
        TESTS_PASSED=$((TESTS_PASSED + 1))
    else
        echo -e "${RED}✗${NC} CONVENTIONAL_LABELS should contain expected labels"
        TESTS_FAILED=$((TESTS_FAILED + 1))
    fi
}

################################################################################
# Main Test Runner
################################################################################

run_all_tests() {
    echo "========================================"
    echo "Running GitHub Label Manager Tests"
    echo "========================================"

    setup

    # Run all tests
    test_github_label_manager_exists
    test_logging_lib_exists
    test_github_label_manager_help
    test_urlencode_function
    test_github_api_call_dry_run
    test_github_api_call_validation
    test_conventional_labels_array

    teardown

    # Print summary
    echo ""
    echo "========================================"
    echo "Test Summary"
    echo "========================================"
    echo "Tests run: $TESTS_RUN"
    echo -e "Tests passed: ${GREEN}$TESTS_PASSED${NC}"
    echo -e "Tests failed: ${RED}$TESTS_FAILED${NC}"

    if [[ $TESTS_FAILED -eq 0 ]]; then
        echo -e "${GREEN}All tests passed!${NC}"
        exit 0
    else
        echo -e "${RED}Some tests failed!${NC}"
        exit 1
    fi
}

# Run tests
run_all_tests
